---
title: "chuyun's part app"
author: "chuyun shu cs3894"
date: "2/14/2021"
output: html_document
---

#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

```{r load libraries and data, warning=FALSE, message=FALSE, include=FALSE}
library(shiny)
library(leaflet)
library(haven)
library(devtools)
library(RColorBrewer)
library(RSocrata)

open_street <- read.socrata("https://data.cityofnewyork.us/Health/Open-Streets-Locations/uiay-nctu")

```


# Define UI for application that maps out openstreets

```{r ui, warning=FALSE}
ui <- fluidPage(

    # Application title
    titlePanel("Map of NYC Open Streets"),

    mainPanel(leafletOutput("map")),
    #Create master panel with different widgets for specification
    absolutePanel(id = "controls", class = "panel panel-default", 
                  fixed = TRUE, draggable = TRUE,
                  top = 80, left = 600, 
                  right = "auto", bottom = "auto", 
                  width = 300, height = "auto",
                  
                 
                              
                  #Widget that filters open streets by borough (can select multiple)
                  span(tags$i(h4("Select Open Streets by Borough"))),
                  checkboxGroupInput("Borough", "Which boroughs are you interested in?",
                                     choices = c("Manhattan", "Brooklyn", "Bronx",
                                                 "Queens", "Staten Island"),
                                     selected = c("Manhattan", "Brooklyn", "Bronx",
                                                  "Queens", "Staten Island")),
                  
                  #Widget that filters openstreets by day of week
                  span(tags$i(h4("Select Open Streets by Day of Week"))),
                  checkboxGroupInput("Day of Week", "What days of the week is this open street becoming public",
                              choices = c("M,T,W,R,F","TWRFSU", "F,S","S,U","FSU","RFSU","ALL"),
                              selected = c("M,T,W,R,F","TWRFSU", "F,S","S,U","FSU","RFSU","ALL")
                  )
    )
)
```

# Run the application 
```{r run app}
shinyApp(ui = ui, server = server)
```